import React, { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { databaseConfigured, deletePortfolioItem, fetchOrders, fetchPortfolio, getSession, insertPortfolioImages, insertPortfolioItem, removePortfolioImage, signIn, signOut, uploadPortfolioImage } from "./supabase";
import "./styles.css";

const IG = "https://instagram.com/herbz108";
const nav = [["Shop", "/"]];
const APPAREL_SIZES = ["XS", "S", "M", "L", "XL", "XXL"];
const euro = cents => cents == null ? "" : new Intl.NumberFormat("nl-BE", { style: "currency", currency: "EUR" }).format(cents / 100);
function go(path) { history.pushState({}, "", path); dispatchEvent(new PopStateEvent("popstate")); scrollTo(0, 0); }
function Link({ to, children, className = "" }) { return <a href={to} className={className} onClick={event => { if (to.startsWith("/")) { event.preventDefault(); go(to); } }}>{children}</a>; }

function Header({ cartCount, onCartOpen }) {
  return <><div className="construction-banner" role="status"><span>Website under construction</span><p>Artwork is available with secure online payment.</p><a href="mailto:herbzbooking@protonmail.com">Questions? Contact us ↗</a></div><header className="site-header"><Link className="logo" to="/"><b>HERBZ108</b><small>Original art / Shop</small></Link><nav aria-label="Main navigation">{nav.map(([label, path]) => <Link key={path} to={path}>{label}</Link>)}</nav><div className="header-actions"><button className="cart-trigger" type="button" onClick={onCartOpen}>Cart <span>{cartCount}</span></button><a className="book-link" href="mailto:herbzbooking@protonmail.com">Contact <span>↗</span></a></div></header></>;
}
function Footer() {
  return <footer className="footer shop-footer"><div className="wrap footer-main"><div><Link className="logo footer-logo" to="/"><b>HERBZ108</b></Link><p>Original work.<br />One of a kind.</p></div><div><p className="footer-label">Shop</p><Link to="/">Available work</Link><button className="footer-cart-link" type="button" onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}>Back to top ↑</button></div><div><p className="footer-label">Purchase enquiries</p><a href="mailto:herbzbooking@protonmail.com">herbzbooking@protonmail.com</a><p>Kasterlee, Belgium</p></div><div><p className="footer-label">Follow</p><a href={IG} target="_blank" rel="noreferrer">Instagram ↗</a></div></div><div className="wrap footer-bottom"><span>© 2026 HERBZ108</span><span>Original artwork from Kasterlee, Belgium.</span></div></footer>;
}
function EmptyState({ category }) { return <div className="empty-gallery"><p className="kicker">Archive in progress</p><h3>New {category} work coming soon.</h3><p>Fresh work will appear here as it leaves the studio.</p></div>; }

function ShopHome({ items, onAdd }) {
  const productTypes = ["paintings", "prints", "apparel", "sculptures", "other"];
  const [activeType, setActiveType] = useState("all");
  const [activeCanvas, setActiveCanvas] = useState("all");
  const canvasTypes = [...new Set(items.filter(item => (item.product_type || "other") === "paintings" && item.canvas_type).map(item => item.canvas_type.trim()).filter(Boolean))];
  const filteredItems = items.filter(item => {
    const matchesType = activeType === "all" || (item.product_type || "other") === activeType;
    const matchesCanvas = activeType !== "paintings" || activeCanvas === "all" || item.canvas_type === activeCanvas;
    return matchesType && matchesCanvas;
  });
  const chooseType = type => { setActiveType(type); setActiveCanvas("all"); };
  return <main className="shop-only"><section className="shop-filters wrap" aria-label="Filter shop products"><p>Browse by category</p><div className="filter-row"><button className={activeType === "all" ? "active" : ""} onClick={() => chooseType("all")}>All</button>{productTypes.map(type => <button key={type} className={activeType === type ? "active" : ""} onClick={() => chooseType(type)}>{type}</button>)}</div>{activeType === "paintings" && canvasTypes.length > 0 && <div className="canvas-filters"><span>Canvas</span><button className={activeCanvas === "all" ? "active" : ""} onClick={() => setActiveCanvas("all")}>All</button>{canvasTypes.map(type => <button key={type} className={activeCanvas === type ? "active" : ""} onClick={() => setActiveCanvas(type)}>{type}</button>)}</div>}</section>
    <section className="shop-catalog wrap" aria-label="Available artwork">{filteredItems.length ? filteredItems.map((item, index) => { const stock = Math.max(0, Number(item.stock_quantity ?? 1)); const needsSize = item.product_type === "apparel"; const availableSizes = needsSize ? APPAREL_SIZES.filter(size => Number(item.size_stock?.[size] || 0) > 0) : []; return <article className={`shop-card ${stock === 0 ? "sold-out" : ""}`} key={item.id}><Link className="shop-card-link" to={`/product/${item.id}`}><div className="shop-card-image"><img src={item.image_url} alt={item.title} /><span>{String(index + 1).padStart(2, "0")}</span>{stock === 0 && <b>Sold out</b>}</div><div className="shop-card-info"><div><h2>{item.title}</h2><p>{item.description}</p>{item.size && <small>{item.size}</small>}{needsSize && availableSizes.length > 0 && <small>Sizes: {availableSizes.join(" / ")}</small>}<small className="stock-label">{stock === 0 ? "No longer available" : needsSize ? "Available" : `${stock} ${stock === 1 ? "piece" : "pieces"} available`}</small></div><strong>{euro(item.price_cents)}</strong></div></Link><button type="button" disabled={stock === 0} onClick={() => needsSize ? go(`/product/${item.id}`) : onAdd({ ...item, stock, src: item.image_url, meta: item.description, unitAmount: item.price_cents })}>{stock === 0 ? "Sold out" : needsSize ? "Choose size" : "Add to cart"} <span>{stock === 0 ? "—" : needsSize ? "→" : "+"}</span></button></article>; }) : <EmptyState category={activeType === "all" ? "artwork" : activeType} />}</section>
    <section className="shop-contact wrap"><p>Questions about a work, dimensions or shipping?</p><a href="mailto:herbzbooking@protonmail.com">herbzbooking@protonmail.com ↗</a></section>
  </main>;
}

function ProductPage({ item, onAdd }) {
  const images = item.images?.length ? item.images : [{ image_url: item.image_url }];
  const coverIndex = Math.max(0, images.findIndex(image => image.is_cover));
  const [selected, setSelected] = useState(coverIndex), [zoomed, setZoomed] = useState(false), [selectedSize, setSelectedSize] = useState("");
  const stock = Math.max(0, Number(item.stock_quantity ?? 1));
  const sizeStock = item.product_type === "apparel" ? (item.size_stock || {}) : {};
  const sizes = APPAREL_SIZES.filter(size => Number(sizeStock[size] || 0) > 0);
  return <main className="product-page wrap"><Link className="product-back" to="/">← Back to shop</Link><section className="product-detail"><div className="product-gallery"><button className="product-main-image" type="button" onClick={() => setZoomed(true)} aria-label="View image fullscreen"><img src={images[selected].image_url} alt={`${item.title} — image ${selected + 1}`} /><span>View fullscreen ↗</span></button>{images.length > 1 && <div className="product-thumbs">{images.map((image, index) => <button type="button" className={selected === index ? "active" : ""} key={image.id || image.image_url} onClick={() => setSelected(index)}><img src={image.image_url} alt={`View ${index + 1}`} /></button>)}</div>}</div><div className="product-copy"><p className="kicker">{item.product_type || "Original work"}</p><h1>{item.title}</h1><strong>{euro(item.price_cents)}</strong>{item.description && <p className="product-description">{item.description}</p>}<dl>{item.canvas_type && <div><dt>Canvas</dt><dd>{item.canvas_type}</dd></div>}{item.size && <div><dt>Size</dt><dd>{item.size}</dd></div>}<div><dt>Availability</dt><dd>{stock === 0 ? "Sold out" : item.product_type === "apparel" ? "Available" : `${stock} ${stock === 1 ? "piece" : "pieces"} available`}</dd></div></dl>{item.product_type === "apparel" && <fieldset className="size-picker"><legend>Choose your size</legend><div>{APPAREL_SIZES.map(size => { const remaining = Number(sizeStock[size] || 0); return <button key={size} type="button" disabled={remaining < 1} className={selectedSize === size ? "active" : ""} onClick={() => setSelectedSize(size)}>{size}{remaining < 1 ? <small>Sold out</small> : remaining <= 3 ? <small>Only {remaining} left</small> : null}</button>; })}</div></fieldset>}<button className="button button-primary product-add" type="button" disabled={stock === 0 || (item.product_type === "apparel" && (!sizes.length || !selectedSize))} onClick={() => onAdd({ ...item, selectedSize: selectedSize || null, cartKey: `${item.id}:${selectedSize || "default"}`, stock: selectedSize ? Number(sizeStock[selectedSize]) : stock, src: item.image_url, meta: item.description, unitAmount: item.price_cents })}>{stock === 0 ? "Sold out" : item.product_type === "apparel" && !selectedSize ? "Choose a size" : "Add to cart ↗"}</button></div></section>{zoomed && <div className="image-lightbox" role="dialog" aria-modal="true" aria-label="Product image"><button type="button" onClick={() => setZoomed(false)} aria-label="Close fullscreen image">×</button><img src={images[selected].image_url} alt={`${item.title} detail`} /></div>}</main>;
}

function Home({ items }) {
  const tattoos = items.filter(x => x.category === "tattoo").slice(0, 3), products = items.filter(x => x.category === "shop").slice(0, 3), recent = items.slice(0, 4);
  return <main><section className="hero" id="home"><div className="hero-art" aria-hidden="true" /><div className="hero-copy wrap"><p className="eyebrow"><span>Kasterlee · BE</span> Tattoo &amp; visual artist</p><h1>Herbz<em>108</em></h1><p className="hero-intro">Original tattoos and raw visual work, built from instinct, contrast and a healthy disrespect for clean edges.</p><div className="actions"><Link className="button button-primary" to="/contact">Book a session <span>↗</span></Link><Link className="button button-ghost" to="/tattoo">View tattoo work</Link></div></div><p className="vertical-note">Independent artist / since 2014</p><a className="scroll-note" href="#work">Scroll to explore ↓</a></section>
    <section className="section wrap" id="work"><div className="section-heading"><div><p className="kicker">01 / Selected work</p><h2>Marked stories</h2></div><p>Custom pieces drawn for the body they live on. Blackwork, illustrative and abstract compositions.</p></div>{tattoos.length ? <div className="work-grid">{tattoos.map((item, index) => <figure className={`work-card work-card-${index + 1}`} key={item.id}><img src={item.image_url} alt={item.title} /><figcaption><span>{String(index + 1).padStart(2, "0")}</span>{item.title}</figcaption></figure>)}</div> : <EmptyState category="tattoo" />}<Link className="text-link" to="/tattoo">Explore the tattoo archive <span>→</span></Link></section>
    <section className="about-preview"><div className="about-image about-artist-photo"><img src="/images/herbz108-about-artist.png" alt="Herbz108 tattooing in his studio" /></div><div className="about-copy"><p className="kicker">02 / Behind the work</p><h2>Made by<br />hand &amp; nerve.</h2><p>I’m an independent tattoo and visual artist working between skin, paper and canvas. My practice is rooted in blackwork, organic shapes and the beauty of imperfection.</p><Link className="text-link dark-link" to="/about">Meet the artist <span>→</span></Link></div></section>
    <section className="section wrap shop-preview"><div className="section-heading"><div><p className="kicker red">03 / Shop drop</p><h2>Objects<br />with a pulse</h2></div><p>One of a kind art.</p></div>{products.length ? <div className="product-row">{products.map(item => <article className="product" key={item.id}><Link to="/shop"><div className="product-image"><img src={item.image_url} alt={item.title} /></div><div className="product-meta"><div><h3>{item.title}</h3><p>{item.description}</p></div><strong>{euro(item.price_cents)}</strong></div></Link></article>)}</div> : <EmptyState category="shop" />}<Link className="button button-ghost" to="/shop">Visit the shop →</Link></section>
    <section className="section wrap recent"><div className="section-heading"><div><p className="kicker">04 / Recent work</p><h2>From the studio</h2></div><p>@herbz108 — process, fresh work and occasional chaos.</p></div>{recent.length ? <div className="insta-grid">{recent.map(item => <a href={IG} target="_blank" rel="noreferrer" key={item.id}><img src={item.image_url} alt={item.title} /><span>↗</span></a>)}</div> : <EmptyState category="studio" />}</section></main>;
}

function GalleryPage({ index, title, intro, items, shop = false, onAdd }) {
  return <main className="inner-page"><header className="page-hero wrap"><p className="kicker">{index} / HERBZ108 studio</p><h1>{title}</h1><p>{intro}</p></header>{items.length ? <section className={`gallery wrap ${shop ? "shop-gallery" : ""}`}>{items.map((item, itemIndex) => <article className="gallery-item" key={item.id}><div className="gallery-image"><img src={item.image_url} alt={item.title} /><span>{String(itemIndex + 1).padStart(2, "0")}</span>{shop && <button type="button" onClick={() => onAdd({ ...item, src: item.image_url, meta: item.description, unitAmount: item.price_cents })}>Add to cart +</button>}</div><div className="gallery-meta"><div><h2>{item.title}</h2><p>{item.description}</p></div>{shop && <strong>{euro(item.price_cents)}</strong>}</div></article>)}</section> : <section className="wrap gallery-empty-wrap"><EmptyState category={shop ? "shop" : title.toLowerCase()} /></section>}<section className="page-cta wrap"><p>Have something specific in mind?</p><h2>Let’s make<br />something yours.</h2><Link className="button button-primary" to="/contact">Start a conversation ↗</Link></section></main>;
}
function About() { return <main className="inner-page"><header className="page-hero wrap"><p className="kicker">04 / About</p><h1>Artist.<br />Mark maker.</h1></header><section className="about-page wrap"><div className="portrait about-artist-photo"><img src="/images/herbz108-about-artist.png" alt="Herbz108 tattooing in his studio" /></div><div className="story"><p className="lead">I make work for people who find beauty in tension: precise and instinctive, quiet and loud, permanent and always changing.</p><p>Based in Kasterlee, I’ve worked independently across tattooing and visual art since 2014. Every tattoo begins with listening. The goal isn’t to impose a house style, but to find the point where your story and my visual language meet.</p><p>Outside the studio I work on paper and canvas, moving between ink, acrylic, found textures and print.</p><dl><div><dt>Focus</dt><dd>Blackwork · Illustrative · Abstract</dd></div><div><dt>Studio</dt><dd>Kasterlee · Private · Appointment only</dd></div><div><dt>Languages</dt><dd>NL · EN</dd></div></dl><Link className="button button-primary" to="/contact">Work with me ↗</Link></div></section></main>; }
function Contact() { return <main className="inner-page contact-page"><header className="page-hero wrap"><p className="kicker">05 / Contact &amp; booking</p><h1>Bring me<br />your idea.</h1><p>Tell me what you’re imagining. Rough thoughts are welcome — we’ll shape the rest together.</p></header><section className="contact-grid wrap"><form onSubmit={event => { event.preventDefault(); alert("Demo form — connect this form to your email or booking service before launch."); }}><div className="form-row"><label>Name<input required placeholder="Your name" /></label><label>Email<input type="email" required placeholder="you@email.com" /></label></div><div className="form-row"><label>Project type<select required defaultValue=""><option value="" disabled>Choose one</option><option>Tattoo booking</option><option>Artwork enquiry</option><option>Commission</option><option>Other</option></select></label><label>Preferred timing<input placeholder="Month / flexible" /></label></div><label>Tell me about it<textarea required rows="7" placeholder="Placement, size, idea, references..." /></label><button className="button button-primary" type="submit">Send enquiry ↗</button></form><aside><p className="footer-label">Direct</p><a href="mailto:herbzbooking@protonmail.com">herbzbooking@protonmail.com</a><p className="footer-label">Studio</p><p>Kasterlee, Belgium<br />Address shared after booking</p></aside></section></main>; }

function Login({ onLogin }) {
  const [email, setEmail] = useState(""), [password, setPassword] = useState(""), [message, setMessage] = useState("");
  async function submit(event) { event.preventDefault(); setMessage("Signing in…"); try { onLogin(await signIn(email, password)); setMessage(""); } catch (error) { setMessage(error.message); } }
  return <main className="admin auth"><section><p className="kicker">Private studio access</p><h1>Admin login.</h1><form onSubmit={submit} className="login-form"><label>Email<input type="email" required autoComplete="email" value={email} onChange={e => setEmail(e.target.value)} /></label><label>Password<input type="password" required autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)} /></label><button className="button button-primary" type="submit">Sign in ↗</button>{message && <p className="form-message">{message}</p>}</form></section></main>;
}
function Admin({ items, onChanged }) {
  const initialForm = { category: "shop", productType: "paintings", canvasType: "", size: "", sizeStock: Object.fromEntries(APPAREL_SIZES.map(size => [size, "0"])), title: "", description: "", price: "", stock: "1" };
  const [session, setSession] = useState(getSession()), [form, setForm] = useState(initialForm), [files, setFiles] = useState([]), [coverIndex, setCoverIndex] = useState(0), [message, setMessage] = useState("");
  const [adminView, setAdminView] = useState("work"), [orders, setOrders] = useState([]), [ordersMessage, setOrdersMessage] = useState("");
  useEffect(() => { if (session && adminView === "orders") { setOrdersMessage("Loading orders…"); fetchOrders().then(data => { setOrders(data); setOrdersMessage(""); }).catch(error => { if (error.message.includes("login expired")) setSession(null); else setOrdersMessage(error.message); }); } }, [adminView, session]);
  if (!databaseConfigured) return <main className="admin"><section><p className="kicker">Setup required</p><h1>Connect database.</h1><p className="notice">Add VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in Netlify to activate secure login and uploads.</p></section></main>;
  if (!session) return <Login onLogin={setSession} />;
  const change = e => setForm({ ...form, [e.target.name]: e.target.value });
  const changeSizeStock = (size, value) => setForm(current => ({ ...current, sizeStock: { ...current.sizeStock, [size]: value } }));
  const chooseFiles = event => { const selected = [...event.target.files]; setFiles(current => [...current, ...selected]); event.target.value = ""; };
  const removeSelectedFile = index => { setFiles(current => current.filter((_, fileIndex) => fileIndex !== index)); setCoverIndex(current => current === index ? 0 : current > index ? current - 1 : current); };
  async function add(event) {
    event.preventDefault(); const formElement = event.currentTarget;
    if (!files.length) return setMessage("Choose at least one image first.");
    if (form.category === "shop" && (!form.price || Number(form.price.replace(",", ".")) < .5)) return setMessage("Enter a valid shop price.");
    if (form.category === "shop" && (!Number.isInteger(Number(form.stock)) || Number(form.stock) < 0)) return setMessage("Enter a valid available quantity.");
    if (form.category === "shop" && form.productType === "apparel" && !Object.values(form.sizeStock).some(value => Number(value) > 0)) return setMessage("Enter stock for at least one apparel size.");
    setMessage("Uploading…"); const uploaded = [];
    try { for (const file of files) { const ext = file.name.split(".").pop().toLowerCase(); const storagePath = `${session.user.id}/${form.category}/${crypto.randomUUID()}.${ext}`; uploaded.push({ image_url: await uploadPortfolioImage(file, storagePath), storage_path: storagePath }); } const cover = uploaded[coverIndex] || uploaded[0]; const apparelStock = Object.fromEntries(APPAREL_SIZES.map(size => [size, Math.max(0, Number(form.sizeStock[size]) || 0)])); const item = await insertPortfolioItem({ category: form.category, product_type: form.category === "shop" ? form.productType : null, canvas_type: form.category === "shop" && form.productType === "paintings" ? form.canvasType.trim() || null : null, size: form.category === "shop" && ["paintings", "prints", "sculptures"].includes(form.productType) ? form.size.trim() || null : null, size_stock: form.category === "shop" && form.productType === "apparel" ? apparelStock : {}, stock_quantity: form.category === "shop" ? (form.productType === "apparel" ? Object.values(apparelStock).reduce((sum, value) => sum + value, 0) : Number(form.stock)) : null, title: form.title, description: form.description, price_cents: form.category === "shop" ? Math.round(Number(form.price.replace(",", ".")) * 100) : null, image_url: cover.image_url, storage_path: cover.storage_path }); await insertPortfolioImages(uploaded.map((image, index) => ({ item_id: item.id, ...image, is_cover: index === coverIndex, sort_order: index }))); setForm(initialForm); setFiles([]); setCoverIndex(0); formElement.reset(); setMessage("Published successfully."); await onChanged(); } catch (error) { await Promise.all(uploaded.map(image => removePortfolioImage(image.storage_path).catch(() => {}))); setMessage(error.message); }
  }
  async function remove(item) { if (!confirm(`Delete ${item.title}?`)) return; setMessage("Deleting…"); try { const imagePaths = (item.images || [{ storage_path: item.storage_path }]).map(image => image.storage_path).filter(Boolean); await deletePortfolioItem(item.id); await onChanged(); const cleanup = await Promise.allSettled(imagePaths.map(path => removePortfolioImage(path))); const storageFailed = cleanup.some(result => result.status === "rejected"); setMessage(storageFailed ? "Item deleted. One or more old image files could not be cleaned up." : "Item deleted."); } catch (error) { setMessage(error.message); } }
  return <main className="admin"><section><div className="admin-heading"><div><p className="kicker">Secure studio access</p><h1>{adminView === "work" ? "Manage work." : "Orders."}</h1></div><button className="button button-ghost" onClick={() => { signOut(); setSession(null); }}>Sign out</button></div>
    <nav className="admin-nav" aria-label="Admin sections"><button type="button" className={adminView === "work" ? "active" : ""} onClick={() => setAdminView("work")}>Manage work</button><button type="button" className={adminView === "orders" ? "active" : ""} onClick={() => setAdminView("orders")}>Orders</button></nav>
    {adminView === "work" ? <><form onSubmit={add} className="admin-form">
      <label>Page<select name="category" value={form.category} onChange={change}><option value="shop">Shop</option><option value="tattoo">Tattoo — hidden</option><option value="art">Art — hidden</option></select></label>
      {form.category === "shop" && <label>Product type<select name="productType" value={form.productType} onChange={change}><option value="paintings">Paintings</option><option value="prints">Prints</option><option value="apparel">Apparel</option><option value="sculptures">Sculptures</option><option value="other">Other</option></select></label>}
      {form.category === "shop" && form.productType === "paintings" && <label>Canvas type<input name="canvasType" value={form.canvasType} onChange={change} placeholder="For example: linen or cotton" /></label>}
      {form.category === "shop" && ["paintings", "prints", "sculptures"].includes(form.productType) && <label>Size<input name="size" required value={form.size} onChange={change} placeholder="For example: 60 × 80 cm" /></label>}
      {form.category === "shop" && form.productType === "apparel" && <fieldset className="admin-size-picker"><legend>Stock per size</legend>{APPAREL_SIZES.map(size => <label key={size}>{size}<input type="number" min="0" step="1" value={form.sizeStock[size]} onChange={event => changeSizeStock(size, event.target.value)} /></label>)}</fieldset>}
      <label>Title<input name="title" required value={form.title} onChange={change} placeholder="Title of the work" /></label><label>Description<input name="description" value={form.description} onChange={change} placeholder="Material, edition…" /></label>{form.category === "shop" && <label>Price in euro<input name="price" inputMode="decimal" required value={form.price} onChange={change} placeholder="85.00" /></label>}{form.category === "shop" && form.productType !== "apparel" && <label>Available quantity<input name="stock" type="number" min="0" step="1" required value={form.stock} onChange={change} /></label>}<label className="file-field">Images<input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={chooseFiles} /><span className="image-upload-help">You can select several photos at once or add them in multiple rounds.</span>{files.length > 0 && <span className="cover-help">Choose the cover image:</span>}{files.map((file, index) => <span className="cover-choice" key={`${file.name}-${file.size}-${index}`}><input type="radio" name="cover" checked={coverIndex === index} onChange={() => setCoverIndex(index)} /><span>{file.name}{coverIndex === index ? " — cover" : ""}</span><button type="button" onClick={() => removeSelectedFile(index)} aria-label={`Remove ${file.name}`}>×</button></span>)}</label><button className="button button-primary" type="submit">Upload &amp; publish ↗</button>{message && <p className="form-message">{message}</p>}</form>
    <div className="admin-lists">{["shop", "tattoo", "art"].map(category => <section key={category}><p className="kicker">{category}</p><h2>{category} work</h2><div className="admin-list">{items.filter(x => x.category === category).map(item => <div key={item.id}><img src={item.image_url} alt="" /><span>{item.title}{item.product_type ? ` · ${item.product_type}` : ""}{item.canvas_type ? ` · ${item.canvas_type}` : ""}{item.images?.length > 1 ? ` · ${item.images.length} photos` : ""}{category === "shop" ? ` · ${item.stock_quantity ?? 1} available` : ""}{item.price_cents ? ` · ${euro(item.price_cents)}` : ""}</span><button onClick={() => remove(item)} aria-label={`Delete ${item.title}`}>×</button></div>)}{!items.some(x => x.category === category) && <p className="empty">No work uploaded yet.</p>}</div></section>)}</div></> : <section className="orders-panel">{ordersMessage && <p className="notice">{ordersMessage}</p>}{!ordersMessage && !orders.length && <p className="empty">No orders received yet.</p>}{orders.map(order => { const address = order.shipping_address; return <article className="order-card" key={order.id}><div className="order-card-head"><div><p className="kicker">{new Date(order.created_at).toLocaleString("nl-BE")}</p><h2>{order.customer_name || order.customer_email || "Customer details unavailable"}</h2>{order.customer_name && <a href={`mailto:${order.customer_email}`}>{order.customer_email}</a>}</div><strong>{euro(order.amount_total)}</strong></div><div className="order-card-body"><div><p className="order-label">Purchased</p><div className="order-items">{(order.items || []).map((orderedItem, index) => { const product = items.find(item => item.id === orderedItem.id); return <p key={`${order.id}-${orderedItem.id || index}`}><span>{orderedItem.quantity} ×</span> {orderedItem.title || product?.title || "Product details unavailable"}{orderedItem.amount_total != null ? ` — ${euro(orderedItem.amount_total)}` : ""}</p>; })}</div></div><address><span className="order-label">Shipping address</span>{address ? <>{address.line1}<br />{address.line2 && <>{address.line2}<br /></>}{address.postal_code} {address.city}<br />{address.state && <>{address.state}<br /></>}{address.country}</> : "Not stored for this earlier order"}</address></div><small>Stripe: {order.stripe_session_id}</small></article>; })}</section>}</section></main>;
}

function CartDrawer({ open, items, onClose, onChange, onRemove }) {
  const [loading, setLoading] = useState(false), [error, setError] = useState(""); const total = items.reduce((sum, item) => sum + item.unitAmount * item.quantity, 0);
  async function checkout() { setLoading(true); setError(""); try { const response = await fetch("/.netlify/functions/create-checkout", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ items: items.map(({ id, quantity, selectedSize }) => ({ id, quantity, size: selectedSize || null })) }) }); const data = await response.json(); if (!response.ok || !data.url) throw new Error(data.error || "Checkout could not be started."); location.href = data.url; } catch (err) { setError(err.message); setLoading(false); } }
  return <div className={`cart-layer ${open ? "open" : ""}`} aria-hidden={!open}><button className="cart-backdrop" onClick={onClose} aria-label="Close cart" /><aside className="cart-drawer"><div className="cart-head"><div><p className="kicker">Your selection</p><h2>Cart</h2></div><button className="cart-close" onClick={onClose}>×</button></div>{!items.length ? <div className="cart-empty"><p>Your cart is still empty.</p></div> : <><div className="cart-items">{items.map(item => { const key = item.cartKey || item.id; return <article className="cart-item" key={key}><img src={item.src} alt="" /><div><h3>{item.title}</h3><p>{item.meta}</p>{item.selectedSize && <p>Size: {item.selectedSize}</p>}<p className="cart-stock">Maximum {item.stock ?? 1} available</p><div className="quantity"><button onClick={() => onChange(key, item.quantity - 1)}>−</button><span>{item.quantity}</span><button disabled={item.quantity >= (item.stock ?? 1)} onClick={() => onChange(key, item.quantity + 1)}>+</button></div></div><div className="cart-item-price"><strong>{euro(item.unitAmount * item.quantity)}</strong><button onClick={() => onRemove(key)}>Remove</button></div></article>; })}</div><div className="cart-summary"><div><span>Total</span><strong>{euro(total)}</strong></div><p>You will continue to Stripe’s secure checkout. Shipping is included in the listed price.</p><button className="button button-primary checkout-button" type="button" disabled={loading} onClick={checkout}>{loading ? "Opening checkout…" : "Secure checkout ↗"}</button>{error && <p className="checkout-error">{error}</p>}</div></>}</aside></div>;
}
function CheckoutSuccess({ onClear }) { useEffect(() => { onClear(); }, []); return <main className="not-found wrap"><p className="kicker">Payment complete</p><h1>Thank you.</h1><p>Your order has been received.</p><Link className="button button-primary" to="/">Back home →</Link></main>; }
function NotFound() { return <main className="not-found wrap"><p className="kicker">404</p><h1>Nothing here.</h1><Link className="button button-primary" to="/">Back home →</Link></main>; }

function App() {
  const [path, setPath] = useState(location.pathname), [portfolio, setPortfolio] = useState([]), [loadingPortfolio, setLoadingPortfolio] = useState(true), [cartOpen, setCartOpen] = useState(false), [cart, setCart] = useState(() => { try { return JSON.parse(localStorage.getItem("herbz108-cart")) || []; } catch { return []; } });
  async function refresh() { try { setPortfolio(await fetchPortfolio()); } catch (error) { console.error(error); } finally { setLoadingPortfolio(false); } }
  useEffect(() => { const update = () => setPath(location.pathname); addEventListener("popstate", update); refresh(); return () => removeEventListener("popstate", update); }, []);
  useEffect(() => { localStorage.setItem("herbz108-cart", JSON.stringify(cart)); }, [cart]);
  function addToCart(product) { if (product.stock < 1) return; const key = product.cartKey || product.id; setCart(current => current.some(x => (x.cartKey || x.id) === key) ? current.map(x => (x.cartKey || x.id) === key ? { ...x, stock: product.stock, quantity: Math.min(x.quantity + 1, product.stock) } : x) : [...current, { ...product, cartKey: key, quantity: 1 }]); setCartOpen(true); }
  const byCategory = category => portfolio.filter(x => x.category === category); let page;
  if (loadingPortfolio && path !== "/admin") page = <main className="not-found wrap"><p className="kicker">Loading studio archive…</p></main>;
  else if (path.startsWith("/product/")) { const item = portfolio.find(product => product.id === decodeURIComponent(path.slice(9))); page = item ? <ProductPage item={item} onAdd={addToCart} /> : <NotFound />; }
  else if (path === "/" || path === "/shop" || path === "/tattoo" || path === "/art" || path === "/about" || path === "/contact") page = <ShopHome items={byCategory("shop")} onAdd={addToCart} />;
  else if (path === "/admin") page = <Admin items={portfolio} onChanged={refresh} />; else if (path === "/checkout/success") page = <CheckoutSuccess onClear={() => setCart([])} />; else page = <NotFound />;
  return <><Header cartCount={cart.reduce((sum, item) => sum + item.quantity, 0)} onCartOpen={() => setCartOpen(true)} />{page}<Footer /><CartDrawer open={cartOpen} items={cart} onClose={() => setCartOpen(false)} onChange={(key, quantity) => setCart(current => quantity < 1 ? current.filter(x => (x.cartKey || x.id) !== key) : current.map(x => (x.cartKey || x.id) === key ? { ...x, quantity: Math.min(quantity, x.stock ?? 1) } : x))} onRemove={key => setCart(current => current.filter(x => (x.cartKey || x.id) !== key))} /></>;
}
createRoot(document.getElementById("root")).render(<App />);
