import React, { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { databaseConfigured, deletePortfolioItem, fetchPortfolio, getSession, insertPortfolioItem, removePortfolioImage, signIn, signOut, uploadPortfolioImage } from "./supabase";
import "./styles.css";

const IG = "https://instagram.com/herbz108";
const nav = [["Tattoo", "/tattoo"], ["Art", "/art"], ["Shop", "/shop"], ["About", "/about"], ["Contact", "/contact"]];
const euro = cents => cents == null ? "" : new Intl.NumberFormat("nl-BE", { style: "currency", currency: "EUR" }).format(cents / 100);
function go(path) { history.pushState({}, "", path); dispatchEvent(new PopStateEvent("popstate")); scrollTo(0, 0); }
function Link({ to, children, className = "" }) { return <a href={to} className={className} onClick={event => { if (to.startsWith("/")) { event.preventDefault(); go(to); } }}>{children}</a>; }

function Header({ cartCount, onCartOpen }) {
  return <><div className="construction-banner" role="status"><span>Website under construction</span><p>Artwork shown is available, but online payment is not active yet.</p><Link to="/contact">Contact to purchase ↗</Link></div><header className="site-header"><Link className="logo" to="/"><b>HERBZ108</b><small>Tattoo / Art</small></Link><nav aria-label="Main navigation">{nav.map(([label, path]) => <Link key={path} to={path}>{label}</Link>)}</nav><div className="header-actions"><button className="cart-trigger" type="button" onClick={onCartOpen}>Cart <span>{cartCount}</span></button><Link className="book-link" to="/contact">Book now <span>↗</span></Link></div><details className="mobile-menu"><summary>Menu</summary><div>{[["Home", "/"], ...nav].map(([label, path]) => <Link key={path} to={path}>{label}</Link>)}</div></details></header></>;
}
function Footer() {
  return <footer className="footer"><div className="wrap footer-main"><div><Link className="logo footer-logo" to="/"><b>HERBZ108</b></Link><p>Permanent marks.<br />Unpolished art.</p></div><div><p className="footer-label">Navigate</p>{[["Home", "/"], ...nav].map(([label, path]) => <Link key={path} to={path}>{label}</Link>)}</div><div><p className="footer-label">Studio</p><p>Kasterlee, BE<br />By appointment only</p><a href="mailto:herbzbooking@protonmail.com">herbzbooking@protonmail.com</a></div><div><p className="footer-label">Follow</p><a href={IG} target="_blank" rel="noreferrer">Instagram ↗</a></div></div><div className="wrap footer-bottom"><span>© 2026 HERBZ108 Studio</span><span>Privacy · Terms</span><span>Built for the beautifully restless.</span></div></footer>;
}
function EmptyState({ category }) { return <div className="empty-gallery"><p className="kicker">Archive in progress</p><h3>New {category} work coming soon.</h3><p>Fresh work will appear here as it leaves the studio.</p></div>; }

function Home({ items }) {
  const tattoos = items.filter(x => x.category === "tattoo").slice(0, 3), products = items.filter(x => x.category === "shop").slice(0, 3), recent = items.slice(0, 4);
  return <main><section className="hero" id="home"><div className="hero-art" aria-hidden="true" /><div className="hero-copy wrap"><p className="eyebrow"><span>Kasterlee · BE</span> Tattoo &amp; visual artist</p><h1>Herbz<em>108</em></h1><p className="hero-intro">Original tattoos and raw visual work, built from instinct, contrast and a healthy disrespect for clean edges.</p><div className="actions"><Link className="button button-primary" to="/contact">Book a session <span>↗</span></Link><Link className="button button-ghost" to="/tattoo">View tattoo work</Link></div></div><p className="vertical-note">Independent artist / since 2014</p><a className="scroll-note" href="#work">Scroll to explore ↓</a></section>
    <section className="section wrap" id="work"><div className="section-heading"><div><p className="kicker">01 / Selected work</p><h2>Marked stories</h2></div><p>Custom pieces drawn for the body they live on. Blackwork, illustrative and abstract compositions.</p></div>{tattoos.length ? <div className="work-grid">{tattoos.map((item, index) => <figure className={`work-card work-card-${index + 1}`} key={item.id}><img src={item.image_url} alt={item.title} /><figcaption><span>{String(index + 1).padStart(2, "0")}</span>{item.title}</figcaption></figure>)}</div> : <EmptyState category="tattoo" />}<Link className="text-link" to="/tattoo">Explore the tattoo archive <span>→</span></Link></section>
    <section className="about-preview"><div className="about-image about-artist-photo"><img src="/images/herbz108-about-artist.png" alt="Herbz108 tattooing in his studio" /></div><div className="about-copy"><p className="kicker">02 / Behind the work</p><h2>Made by<br />hand &amp; nerve.</h2><p>I’m an independent tattoo and visual artist working between skin, paper and canvas. My practice is rooted in blackwork, organic shapes and the beauty of imperfection.</p><Link className="text-link dark-link" to="/about">Meet the artist <span>→</span></Link></div></section>
    <section className="section wrap shop-preview"><div className="section-heading"><div><p className="kicker red">03 / Shop drop</p><h2>Objects<br />with a pulse</h2></div><p>One of a kind art.</p></div>{products.length ? <div className="product-row">{products.map(item => <article className="product" key={item.id}><Link to="/shop"><div className="product-image"><img src={item.image_url} alt={item.title} /></div><div className="product-meta"><div><h3>{item.title}</h3><p>{item.description}</p></div><strong>{euro(item.price_cents)}</strong></div></Link></article>)}</div> : <EmptyState category="shop" />}<Link className="button button-ghost" to="/shop">Visit the shop →</Link></section>
    <section className="section wrap recent"><div className="section-heading"><div><p className="kicker">04 / Recent work</p><h2>From the studio</h2></div><p>@herbz108 — process, fresh work and occasional chaos.</p></div>{recent.length ? <div className="insta-grid">{recent.map(item => <a href={IG} target="_blank" rel="noreferrer" key={item.id}><img src={item.image_url} alt={item.title} /><span>↗</span></a>)}</div> : <EmptyState category="studio" />}</section></main>;
}

function GalleryPage({ index, title, intro, items, shop = false, onAdd }) {
  return <main className="inner-page"><header className="page-hero wrap"><p className="kicker">{index} / HERBZ108 studio</p><h1>{title}</h1><p>{intro}</p></header>{items.length ? <section className={`gallery wrap ${shop ? "shop-gallery" : ""}`}>{items.map((item, itemIndex) => <article className="gallery-item" key={item.id}><div className="gallery-image"><img src={item.image_url} alt={item.title} /><span>{String(itemIndex + 1).padStart(2, "0")}</span>{shop && <button type="button" onClick={() => onAdd({ ...item, src: item.image_url, meta: item.description, unitAmount: item.price_cents })}>Add to cart +</button>}</div><div className="gallery-meta"><div><h2>{item.title}</h2><p>{item.description}</p></div>{shop && <strong>{euro(item.price_cents)}</strong>}</div></article>)}</section> : <section className="wrap gallery-empty-wrap"><EmptyState category={shop ? "shop" : title.toLowerCase()} /></section>}<section className="page-cta wrap"><p>Have something specific in mind?</p><h2>Let’s make<br />something yours.</h2><Link className="button button-primary" to="/contact">Start a conversation ↗</Link></section></main>;
}
function About() { return <main className="inner-page"><header className="page-hero wrap"><p className="kicker">04 / About</p><h1>Artist.<br />Mark maker.</h1></header><section className="about-page wrap"><div className="portrait about-artist-photo"><img src="/images/herbz108-about-artist.png" alt="Herbz108 tattooing in his studio" /></div><div className="story"><p className="lead">I make work for people who find beauty in tension: precise and instinctive, quiet and loud, permanent and always changing.</p><p>Based in Kasterlee, I’ve worked independently across tattooing and visual art since 2014. Every tattoo begins with listening. The goal isn’t to impose a house style, but to find the point where your story and my visual language meet.</p><p>Outside the studio I work on paper and canvas, moving between ink, acrylic, found textures and print.</p><dl><div><dt>Focus</dt><dd>Blackwork · Illustrative · Abstract</dd></div><div><dt>Studio</dt><dd>Kasterlee · Private · Appointment only</dd></div><div><dt>Languages</dt><dd>NL · EN</dd></div></dl><Link className="button button-primary" to="/contact">Work with me ↗</Link></div></section></main>; }
function Contact() { return <main className="inner-page contact-page"><header className="page-hero wrap"><p className="kicker">05 / Contact &amp; booking</p><h1>Bring me<br />your idea.</h1><p>Tell me what you’re imagining. Rough thoughts are welcome — we’ll shape the rest together.</p></header><section className="contact-grid wrap"><form onSubmit={event => { event.preventDefault(); alert("Demo form — connect this form to your email or booking service before launch."); }}><div className="form-row"><label>Name<input required placeholder="Your name" /></label><label>Email<input type="email" required placeholder="you@email.com" /></label></div><div className="form-row"><label>Project type<select required defaultValue=""><option value="" disabled>Choose one</option><option>Tattoo booking</option><option>Artwork enquiry</option><option>Commission</option><option>Other</option></select></label><label>Preferred timing<input placeholder="Month / flexible" /></label></div><label>Tell me about it<textarea required rows="7" placeholder="Placement, size, idea, references..." /></label><button className="button button-primary" type="submit">Send enquiry ↗</button></form><aside><p className="footer-label">Direct</p><a href="mailto:herbzbooking@protonmail.com">herbzbooking@protonmail.com</a><p className="footer-label">Studio</p><p>Kasterlee, Belgium<br />Address shared after booking</p></aside></section></main>; }

function Login({ onLogin }) {
  const [email, setEmail] = useState(""), [password, setPassword] = useState(""), [message, setMessage] = useState("");
  async function submit(event) { event.preventDefault(); setMessage("Signing in…"); try { onLogin(await signIn(email, password)); setMessage(""); } catch (error) { setMessage(error.message); } }
  return <main className="admin auth"><section><p className="kicker">Private studio access</p><h1>Admin login.</h1><form onSubmit={submit} className="login-form"><label>Email<input type="email" required autoComplete="email" value={email} onChange={e => setEmail(e.target.value)} /></label><label>Password<input type="password" required autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)} /></label><button className="button button-primary" type="submit">Sign in ↗</button>{message && <p className="form-message">{message}</p>}</form></section></main>;
}
function Admin({ items, onChanged }) {
  const [session, setSession] = useState(getSession()), [form, setForm] = useState({ category: "tattoo", title: "", description: "", price: "", sortOrder: "0" }), [file, setFile] = useState(null), [message, setMessage] = useState("");
  if (!databaseConfigured) return <main className="admin"><section><p className="kicker">Setup required</p><h1>Connect database.</h1><p className="notice">Add VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in Netlify to activate secure login and uploads.</p></section></main>;
  if (!session) return <Login onLogin={setSession} />;
  const change = e => setForm({ ...form, [e.target.name]: e.target.value });
  async function add(event) {
    event.preventDefault(); const formElement = event.currentTarget;
    if (!file) return setMessage("Choose an image first.");
    if (form.category === "shop" && (!form.price || Number(form.price.replace(",", ".")) < .5)) return setMessage("Enter a valid shop price.");
    setMessage("Uploading…"); const ext = file.name.split(".").pop().toLowerCase(); const storagePath = `${session.user.id}/${form.category}/${crypto.randomUUID()}.${ext}`;
    try { const imageUrl = await uploadPortfolioImage(file, storagePath); await insertPortfolioItem({ category: form.category, title: form.title, description: form.description, price_cents: form.category === "shop" ? Math.round(Number(form.price.replace(",", ".")) * 100) : null, image_url: imageUrl, storage_path: storagePath, sort_order: Number(form.sortOrder) || 0 }); setForm({ category: "tattoo", title: "", description: "", price: "", sortOrder: "0" }); setFile(null); formElement.reset(); setMessage("Published successfully."); await onChanged(); } catch (error) { await removePortfolioImage(storagePath).catch(() => {}); setMessage(error.message); }
  }
  async function remove(item) { if (!confirm(`Delete ${item.title}?`)) return; setMessage("Deleting…"); try { await deletePortfolioItem(item.id); await removePortfolioImage(item.storage_path); setMessage("Item deleted."); await onChanged(); } catch (error) { setMessage(error.message); } }
  return <main className="admin"><section><div className="admin-heading"><div><p className="kicker">Secure studio access</p><h1>Manage work.</h1></div><button className="button button-ghost" onClick={() => { signOut(); setSession(null); }}>Sign out</button></div><form onSubmit={add} className="admin-form"><label>Page<select name="category" value={form.category} onChange={change}><option value="tattoo">Tattoo</option><option value="art">Art</option><option value="shop">Shop</option></select></label><label>Title<input name="title" required value={form.title} onChange={change} placeholder="Title of the work" /></label><label>Description<input name="description" value={form.description} onChange={change} placeholder="Style, placement, material…" /></label>{form.category === "shop" && <label>Price in euro<input name="price" inputMode="decimal" required value={form.price} onChange={change} placeholder="85.00" /></label>}<label>Order<input name="sortOrder" type="number" value={form.sortOrder} onChange={change} /></label><label className="file-field">Image<input type="file" accept="image/jpeg,image/png,image/webp" required onChange={e => setFile(e.target.files[0])} /></label><button className="button button-primary" type="submit">Upload &amp; publish ↗</button>{message && <p className="form-message">{message}</p>}</form><div className="admin-lists">{["tattoo", "art", "shop"].map(category => <section key={category}><p className="kicker">{category}</p><h2>{category} work</h2><div className="admin-list">{items.filter(x => x.category === category).map(item => <div key={item.id}><img src={item.image_url} alt="" /><span>{item.title}{item.price_cents ? ` · ${euro(item.price_cents)}` : ""}</span><button onClick={() => remove(item)} aria-label={`Delete ${item.title}`}>×</button></div>)}{!items.some(x => x.category === category) && <p className="empty">No work uploaded yet.</p>}</div></section>)}</div></section></main>;
}

function CartDrawer({ open, items, onClose, onChange, onRemove }) {
  const [loading, setLoading] = useState(false), [error, setError] = useState(""); const total = items.reduce((sum, item) => sum + item.unitAmount * item.quantity, 0);
  async function checkout() { setLoading(true); setError(""); try { const response = await fetch("/.netlify/functions/create-checkout", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ items: items.map(({ id, quantity }) => ({ id, quantity })) }) }); const data = await response.json(); if (!response.ok || !data.url) throw new Error(data.error || "Checkout could not be started."); location.href = data.url; } catch (err) { setError(err.message); setLoading(false); } }
  return <div className={`cart-layer ${open ? "open" : ""}`} aria-hidden={!open}><button className="cart-backdrop" onClick={onClose} aria-label="Close cart" /><aside className="cart-drawer"><div className="cart-head"><div><p className="kicker">Your selection</p><h2>Cart</h2></div><button className="cart-close" onClick={onClose}>×</button></div>{!items.length ? <div className="cart-empty"><p>Your cart is still empty.</p></div> : <><div className="cart-items">{items.map(item => <article className="cart-item" key={item.id}><img src={item.src} alt="" /><div><h3>{item.title}</h3><p>{item.meta}</p><div className="quantity"><button onClick={() => onChange(item.id, item.quantity - 1)}>−</button><span>{item.quantity}</span><button onClick={() => onChange(item.id, item.quantity + 1)}>+</button></div></div><div className="cart-item-price"><strong>{euro(item.unitAmount * item.quantity)}</strong><button onClick={() => onRemove(item.id)}>Remove</button></div></article>)}</div><div className="cart-summary"><div><span>Total</span><strong>{euro(total)}</strong></div>{error && <p className="checkout-error">{error}</p>}<button className="button button-primary checkout-button" onClick={checkout} disabled={loading}>{loading ? "Opening checkout…" : "Proceed to payment ↗"}</button></div></>}</aside></div>;
}
function CheckoutSuccess({ onClear }) { useEffect(() => { onClear(); }, []); return <main className="not-found wrap"><p className="kicker">Payment complete</p><h1>Thank you.</h1><p>Your order has been received.</p><Link className="button button-primary" to="/">Back home →</Link></main>; }
function NotFound() { return <main className="not-found wrap"><p className="kicker">404</p><h1>Nothing here.</h1><Link className="button button-primary" to="/">Back home →</Link></main>; }

function App() {
  const [path, setPath] = useState(location.pathname), [portfolio, setPortfolio] = useState([]), [loadingPortfolio, setLoadingPortfolio] = useState(true), [cartOpen, setCartOpen] = useState(false), [cart, setCart] = useState(() => { try { return JSON.parse(localStorage.getItem("herbz108-cart")) || []; } catch { return []; } });
  async function refresh() { try { setPortfolio(await fetchPortfolio()); } catch (error) { console.error(error); } finally { setLoadingPortfolio(false); } }
  useEffect(() => { const update = () => setPath(location.pathname); addEventListener("popstate", update); refresh(); return () => removeEventListener("popstate", update); }, []);
  useEffect(() => { localStorage.setItem("herbz108-cart", JSON.stringify(cart)); }, [cart]);
  function addToCart(product) { setCart(current => current.some(x => x.id === product.id) ? current.map(x => x.id === product.id ? { ...x, quantity: x.quantity + 1 } : x) : [...current, { ...product, quantity: 1 }]); setCartOpen(true); }
  const byCategory = category => portfolio.filter(x => x.category === category); let page;
  if (loadingPortfolio && path !== "/admin") page = <main className="not-found wrap"><p className="kicker">Loading studio archive…</p></main>;
  else if (path === "/") page = <Home items={portfolio} />;
  else if (path === "/tattoo") page = <GalleryPage index="01" title="Tattoo archive" intro="Custom blackwork, illustrative and abstract pieces, designed in dialogue with every client and every body." items={byCategory("tattoo")} />;
  else if (path === "/art") page = <GalleryPage index="02" title="Art / experiments" intro="A wider archive of originals, studies and visual experiments." items={byCategory("art")} />;
  else if (path === "/shop") page = <GalleryPage index="03" title="Shop the work" intro="Originals and limited editions. Pay securely through Stripe." items={byCategory("shop")} shop onAdd={addToCart} />;
  else if (path === "/about") page = <About />; else if (path === "/contact") page = <Contact />; else if (path === "/admin") page = <Admin items={portfolio} onChanged={refresh} />; else if (path === "/checkout/success") page = <CheckoutSuccess onClear={() => setCart([])} />; else page = <NotFound />;
  return <><Header cartCount={cart.reduce((sum, item) => sum + item.quantity, 0)} onCartOpen={() => setCartOpen(true)} />{page}<Footer /><CartDrawer open={cartOpen} items={cart} onClose={() => setCartOpen(false)} onChange={(id, quantity) => setCart(current => quantity < 1 ? current.filter(x => x.id !== id) : current.map(x => x.id === id ? { ...x, quantity } : x))} onRemove={id => setCart(current => current.filter(x => x.id !== id))} /></>;
}
createRoot(document.getElementById("root")).render(<App />);
